export const BUTTON_SAVE_REQUEST = 'BUTTON_SAVE_REQUEST';

export const BUTTON_SAVE_SUCCESS = 'BUTTON_SAVE_SUCCESS';
export const BUTTON_SAVE_FAIL = 'BUTTON_SAVE_FAIL';
export const BUTTON_SAVE_RESET = 'BUTTON_SAVE_RESET';

export const BUTTON_BLOCK_REQUEST = 'BUTTON_BLOCK_REQUEST';
export const BUTTON_BLOCK_SUCCESS = 'BUTTON_BLOCK_SUCCESS';
export const BUTTON_BLOCK_FAIL = 'BUTTON_BLOCK_FAIL';
