export const MESSAGE_GET_REQUEST = "MESSAGE_GET_REQUEST";
export const MESSAGE_FETCH_GET_SUCCESS = "MESSAGE_FETCH_GET_SUCCESS";
export const MESSAGE_SEND_GET_SUCCESS = "MESSAGE_SEND_GET_SUCCESS";

export const MESSAGE_GET_FAIL = "MESSAGE_GET_FAIL";
