export const MESSAGE_GET_REQUEST = "MESSAGE_GET_REQUEST";
export const MESSAGE_FETCH_GET_SUCCESS = "MESSAGE_FETCH_GET_SUCCESS";
export const MESSAGE_SEND_GET_SUCCESS = "MESSAGE_SEND_GET_SUCCESS";
export const MESSAGE_LOG_SUCCESS = "MESSAGE_LOG_SUCCESS";

export const MESSAGE_GET_FAIL = "MESSAGE_GET_FAIL";

export const MESSAGE_INITIATE = "MESSAGE_INITIATE";
