export const MESSAGE_INITIATE = "MESSAGE_INITIATE";

export const MESSAGE_LOG_FAIL = "MESSAGE_LOG_FAIL";
export const MESSAGE_LOG_REQUEST = "MESSAGE_LOG_REQUEST";
export const MESSAGE_LOG_SUCCESS = "MESSAGE_LOG_SUCCESS";

export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST";
export const MESSAGE_SEND_FAIL = "MESSAGE_SEND_FAIL";

export const MESSAGE_GET_HISTORY_SUCCESS = "MESSAGE_GET_HISTORY_SUCCESS";
export const MESSAGE_GET_HISTORY_REQUEST = "MESSAGE_GET_HISTORY_REQUEST";
export const MESSAGE_GET_HISTORY_FAIL = "MESSAGE_GET_HISTORY_FAIL";
