export const MESSAGE_INITIATE = 'MESSAGE_INITIATE';

export const MESSAGE_LOG_FAIL = 'MESSAGE_LOG_FAIL';
export const MESSAGE_LOG_REQUEST = 'MESSAGE_LOG_REQUEST';
export const MESSAGE_LOG_SUCCESS = 'MESSAGE_LOG_SUCCESS';

export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST';
export const MESSAGE_SEND_FAIL = 'MESSAGE_SEND_FAIL';

export const MESSAGE_GET_HISTORY_SUCCESS = 'MESSAGE_GET_HISTORY_SUCCESS';
export const MESSAGE_GET_HISTORY_REQUEST = 'MESSAGE_GET_HISTORY_REQUEST';
export const MESSAGE_GET_HISTORY_FAIL = 'MESSAGE_GET_HISTORY_FAIL';

export const SOCKET_REQUEST = 'SOCKET_REQUEST';
export const SOCKET_SUCCESS = 'SOCKET_SUCCESS';
export const SOCKET_FAIL = 'SOCKET_FAIL';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_SUBSCRIBE = 'SOCKET_SUBSCRIBE';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_RELATION = 'SOCKET_RELATION';
export const SOCKET_SEND = 'SOCKET_SEND';
export const SOCKET_FETCH = 'SOCKET_FETCH';
export const SOCKET_GET = 'SOCKET_GET';
export const MESSAGE_GET_HISTORY_RESET = 'MESSAGE_GET_HISTORY_RESET';
