export const PEOPLE_LIST_REQUEST = 'PEOPLE_LIST_REQUEST';

export const PEOPLE_LIST_SUCCESS = 'PEOPLE_LIST_SUCCESS';
export const PEOPLE_LIST_FAIL = 'PEOPLE_LIST_FAIL';

export const PEOPLE_LIST_RESET = 'PEOPLE_LIST_RESET';
