export const SAVE_LIST_REQUEST = 'SAVE_LIST_REQUEST';

export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';
export const SAVE_LIST_FAIL = 'SAVE_LIST_FAIL';
export const SAVE_LIST_RESET = 'SAVE_LIST_RESET';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';

export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL';
