export const SECURITY_PASSWORD_REQUEST = "SECURITY_PASSWORD_REQUEST";
export const SECURITY_PASSWORD_SUCCESS = "SECURITY_PASSWORD_SUCCESS";
export const SECURITY_PASSWORD_FAIL = "SECURITY_PASSWORD_FAIL";
export const SECURITY_PASSWORD_RESET = "SECURITY_PASSWORD_RESET";

export const SECURITY_UPLOAD_PROFILE_REQUEST =
  "SECURITY_UPLOAD_PROFILE_REQUEST";

export const SECURITY_UPLOAD_PROFILE_SUCCESS =
  "SECURITY_UPLOAD_PROFILE_SUCCESS";
export const SECURITY_UPLOAD_PROFILE_FAIL = "SECURITY_UPLOAD_PROFILE_FAIL";

export const SECURITY_PERSONALINFO_REQUEST = "SECURITY_PERSONALINFO_REQUEST";
export const SECURITY_PERSONALINFO_SUCCESS = "SECURITY_PERSONALINFO_SUCCESS";
export const SECURITY_PERSONALINFO_FAIL = "SECURITY_PASSWORD_FAIL";
