export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_EMAIL_REQUEST = "USER_EMAIL_REQUEST";

export const USER_EMAIL_SUCCESS = "USER_EMAIL_SUCCESS";
export const USER_EMAIL_FAIL = "USER_EMAIL_FAIL";
